//SSL Protocols and Ciphers for client side communication.

//The following are the default supported SSL Protocols and Ciphers.
SSLProtocols=TLSv1_3:TLSv1_2
SSLCiphers=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

SSLProtocolsFIPS=TLSv1_3:TLSv1_2
SSLCiphersFIPS=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

//Due to the Lucky 13 attack, BEAST attack and SSL/TLS Renegotiation Denial of Service Exploit, 
//the default set of ciphers include only those created with GCM with the exception 
//of the four originally supported CBC ciphers added for backwards compatibility.
//For full protection from the Lucky 13 attack, BEAST attack and 
//SSL/TLS Renegotiation Denial of Service Exploit, it is ecommended that the following ciphers 
//be removed from the above SSLCiphers and SSLCiphersFIPS strings:
//TLS_RSA_With_AES_256_CBC_SHA256, TLS_RSA_With_AES_256_CBC_SHA,
//TLS_RSA_With_AES_128_CBC_SHA256 and TLS_RSA_With_AES_128_CBC_SHA.

//Protocol SSLv3 and ciphers TLS_RSA_With_RC4_SHA and TLS_RSA_With_RC4_MD5 are not a
//part of the default configuration but they were available for use in 
//previous releases.  They are no longer considered safe by RSA and should
//not be used.  However, if they are needed due to a legacy configuration then
//they can be added back but it is not recommended.

//Use PKIX TrustManager and KeyManager instead of default Sun X509
usePKIXTrustManager=false

//Uncomment the below property for enabling host name verification during backchannel SSL communication
//EnableSSLHostnameVerification=true

//uncomment below properties to enforce proxy for oauth transactions(set oauth or jwks or none as useProxy value)
//when useProxy is set to oauth, the proxy will be enforced for the oauth transactions for outbound internet connection
//when useProxy is set to jwks, the proxy will be enforced for the jwks endpoint consumption transactions in Policy Server
//when useProxy is set to none, the proxy will not be enforced

useProxy=oauth

//Proxy Configuration details for backchannel communication. Provide mandatory details (i.e ProxyHost)

ProxyHost=
ProxyPort=
ProxyUser=
ProxyPassword=

//JWKS Configuration
//CacheTime specifies the time interval after which SiteMinder periodically retrieves data from a JWKS endpoint. Enter a value above 0, default value is 6.
//CacheTimeUnit specifies time interval unit for CacheTime. Possible values are HOURS, and DAYS. Default value is HOURS.
//SSLVerifyOFF specifies whether SSL verification between Policy Server and the configured JWKS endpoint is enabled. Enter true or false, default value is false.
//CacheTime=6
//CacheTimeUnit=HOURS
//SSLVerifyOFF=true
